# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Apuntes de licenciatura en biología por rivel_co.

# Email
email: includepoetry@protonmail.com

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: G-K1004SGVH0

# Base del sitio
url: "https://www.include-poetry.com"
baseurl: /Notes

# Excuidos de la conversión
exclude:
  - vendor

# Gemas
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Algolia - buscador
algolia:
  application_id: 'QC3QNXU3KT'
  index_name: 'MainIndexIPN'
  excluded_files:
    - 404.md
    - Buscador/index.html
    - Biologia-celular/index.html
    - Biologia-celular/Tags/index.html
    - Biologia-procariontes/index.html
    - Biologia-procariontes/Tags/index.html
    - Bioquimica-basica/index.html
    - Bioquimica-basica/Tags/index.html
    - Fisicoquimica-biologica/index.html
    - Fisicoquimica-biologica/Tags/index.html
    - Introduccion-biologia/index.html
    - Introduccion-biologia/Tags/index.html
  record_css_selector: 'p,ul,ol,blockquote,table'
  settings:
    attributesForFaceting:
      - tags
      - olimpiada
      - subject
      - author

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "https://www.include-poetry.com/IP-Sources"

# Colecciones
collections:
  Intro-bio:
    output: true
    permalink: /Introduccion-biologia/:title/
  B-Celular:
    output: true
    permalink: /Biologia-celular/:title/
  B-Procariontes:
    output: true
    permalink: /Biologia-procariontes/:title/
  BioquimicaB:
    output: true
    permalink: /Bioquimica-basica/:title/
  FQB:
    output: true
    permalink: /Fisicoquimica-biologica/:title/
