# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Apuntes de licenciatura en biología por rivel_co.

# Email
email: includepoetry@gmail.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio url: "http://localhost:4000" url: "http://169.254.223.56:4000"
url: "http://192.168.1.64:4000"
baseurl: "/Notes"
host: 0.0.0.0

# Excuidos de la conversión
exclude: [Montar.bat, IP-Notes.sublime-project, IP-Notes.sublime-workspace]

#incremental: true;

# paginate: 8
# paginate_path: "/Blog/Pagina-:num/"

# Gemas
# gems: jekyll-paginate-v2

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "/Notes/RecursosDev"

# :categories/:year/:month/:day/

# Colecciones
collections:
  Intro-bio:
    output: true
    permalink: /Introduccion-biologia/:title/
  B-Celular:
    output: true
    permalink: /Biologia-celular/:title/
  B-Procariontes:
    output: true
    permalink: /Biologia-procariontes/:title/
  BioquimicaB:
    output: true
    permalink: /Bioquimica-basica/:title/
  C-Integral:
    output: true
    permalink: /Calculo-integral/:title/
  FQB:
    output: true
    permalink: /Fisicoquimica-biologica/:title/